### ISSUE TITLE
Issue BmbSearchInputComponent

### ISSUE THREAD

**Issue by OsvaldoITESM** [ti-tecnologico-de-monterrey-oficial/tec-design-system-ng#131]
**componente:** BmbSearchInputComponent

**Requerimientos**:  La  funcionalidad que requerimos es que pueda escribir texto en el text input y mediante el icono de la lupa con el que cuenta el componente  este pueda contar con un evento donde pueda mandar a llamar un metodo 

<img width="688" alt="image" src="https://github.com/user-attachments/assets/6ccd1d96-ade3-49ac-a867-b5fb59cf6ad9">

**Comment by t-juansanchez** [comment]
El campo que comentas no está pensado para realizar esa funcionalidad, pero lo tomaremos en cuenta para agregar una funcionalidad a otro input
