### ISSUE TITLE
Issue BmbTabsComponent

### ISSUE THREAD

**Issue by OsvaldoITESM** [ti-tecnologico-de-monterrey-oficial/tec-design-system-ng#132]
**Componente**: BmbTabsComponent

**Issue**: Al utilizar el componente BmbTabsComponent dentro de una card<bmb-card bmbLayoutItem [colLg]="9" [colSm]="4" [borderRadius]="'m'" [margin]="'m'" [type]="'secondary'"> y contando con otra <bmb-card bmbLayoutItem [colLg]="3" [colSm]="4" [borderRadius]="'m'" [margin]="'m'" [type]="'secondary'"> los tabs que no son visibles hace que mi card con [colLg]="3" se posiciones en la parte de abajo, y en la vista de mobile los tabs no son reposivos, adjunto imagenes de muestra.

**Requerimientos**: que los tabs sean responsivo tal ves que se agrupen hacia abajo en lugar de un scroll horizontal

![image](https://github.com/user-attachments/assets/859b7431-d5eb-4f02-ae39-507247811fba)

<img width="715" alt="image" src="https://github.com/user-attachments/assets/8eadfd01-f3a2-4e49-ab86-088f363f39c4">

<img width="163" alt="image" src="https://github.com/user-attachments/assets/3e612b9c-9c68-4889-beb7-698a9ee08308">

![image](https://github.com/user-attachments/assets/a9fdbe5e-04be-4a27-8bc9-830ecc77f6c4)

**Comment by t-juansanchez** [comment]
En la versión 1.0.3 es posible hacer scroll en las tabs, es importante pensar que la cantidad de tabs no debería ser tanta como para hacer un scroll demasiado grande.
![image](https://github.com/user-attachments/assets/70dd6fa9-399a-4941-9cbb-d1d1a8268198)
