### ISSUE TITLE
Issue BmbSidebarComponent

### ISSUE THREAD

**Issue by OsvaldoITESM** [ti-tecnologico-de-monterrey-oficial/tec-design-system-ng#133]
**Componente**: BmbSidebarComponent

**Issue**: Al actualizar la Bamboo el BmbSidebarComponent al momento de expander el sideBar muestra la palabra Navigation esta podria se configurable para pode cambiar su valos, adjuntos imagen

![image](https://github.com/user-attachments/assets/33999fc0-de13-4a0d-857f-22831a5c38e2)

**Comment by t-juansanchez** [comment]
Actualiza la versión de tu librería, en la versión actual (0.4.2) ya soporta la personalización del título.

![image](https://github.com/user-attachments/assets/b18a53e7-40fc-4f35-9cc9-e24cb0292ea7)

![image](https://github.com/user-attachments/assets/a73bd926-e64f-48c9-a860-43c665ece7ac)
