### ISSUE TITLE
Issue BmbIconComponent

### ISSUE THREAD

**Issue by OsvaldoITESM** [ti-tecnologico-de-monterrey-oficial/tec-design-system-ng#178]
Componente: BmbIconComponent

Issue: Al actualizar la Bambooa la version 1.0.3 el BmbIconComponent al momento de querer usar ciertos iconos no lo pinta de manera adecuada. estos son algunos iconos que identifique que nos lo puedo utilizar

![image](https://github.com/user-attachments/assets/9d9561e2-6eb5-4bd6-9926-8235755dbbf8)
![image](https://github.com/user-attachments/assets/ecd7efd4-2cb5-4f3a-a647-accec5529e88)
![image](https://github.com/user-attachments/assets/c65c4237-41f3-4d36-adb3-434b8ccb1e34)

**Comment by t-juansanchez** [comment]
Arreglado en la versión  1.0.10 o superior
