### ISSUE TITLE
Issue BmbModalComponent

### ISSUE THREAD

**Issue by OsvaldoITESM** [ti-tecnologico-de-monterrey-oficial/tec-design-system-ng#179]
**Componente**: BmbModalComponent

**Issue**: Al utilizar el BmbModalComponent no toma en cuenta la propiedad type = alert y alert style=warning, error, success, siempre se muestra el modal sin tomar loas cambios en esas propiedades 

![image](https://github.com/user-attachments/assets/20873f1b-49de-496b-a9a7-5bbdcd853465)

**Comment by t-juansanchez** [comment]
https://tecdemonterrey.atlassian.net/browse/DS01-1655

**Comment by t-juansanchez** [comment]
Fix disponible en la version 1.1.3
