### ISSUE TITLE
Bug/Issue BmbToastComponent

### ISSUE THREAD

**Issue by JorgeV-TEC** [ti-tecnologico-de-monterrey-oficial/tec-design-system-ng#185]
**Describe the bug**
El componente al tenerlo en componentes hijos, no se sobrepone, queda atras visualmente

**To Reproduce**
en este caso es con el stepperComponent, pero hay otros componentes donde si esta por encima y otros no

**Screenshots**
![image](https://github.com/user-attachments/assets/dfdfab6b-b4a9-4435-93b3-c823eeceeeeb)

**Comment by t-juansanchez** [comment]
https://tecdemonterrey.atlassian.net/browse/DS01-1653

**Comment by t-juansanchez** [comment]
Corrección disponible en la versión 1.2.2, contiene **breaking changes**
