### ISSUE TITLE
Issue BmbLayoutDirective

### ISSUE THREAD

**Issue by OsvaldoITESM** [ti-tecnologico-de-monterrey-oficial/tec-design-system-ng#245]
**Describe the bug**
Al utilizar los componentes de dropdown y input with tags dentro de la directiva BmbLayoutDirective, se genera el siguiente issue cuando se abre para ver las opciones se genera un doble srcoll y las opciones no se sobre ponen.

**To Reproduce**

https://github.com/user-attachments/assets/73e3f257-79e4-496f-a170-f7ff326888c4

**Comment by t-juansanchez** [comment]
Resuelto en la versión 1.2.1
