### ISSUE TITLE
Bamboo Modal component

### ISSUE THREAD

**Issue by neftec99** [ti-tecnologico-de-monterrey-oficial/tec-design-system-ng#249]
**Describe the bug**
Dejo de funcionar el modal en la versión de Bamboo 1.2 

Error:
R3InjectorError(Standalone[_BmbModalComponent])[MatDialogRef -> MatDialogRef -> MatDialogRef]: 
  NullInjectorError: No provider for MatDialogRef!
    at NullInjector.get (core.mjs:1636:21)
    at R3Injector.get (core.mjs:3018:27)
    at R3Injector.get (core.mjs:3018:27)
    at R3Injector.get (core.mjs:3018:27)
    at ChainedInjector.get (core.mjs:5289:32)
    at lookupTokenUsingModuleInjector (core.mjs:5632:31)
    at getOrCreateInjectable (core.mjs:5678:10)
    at ɵɵdirectiveInject (core.mjs:11577:17)
    at NodeInjectorFactory.BmbModalComponent_Factory [as factory] (ti-tecnologico-de-monterrey-oficial-ds-ng.mjs:9420:62)
    at getNodeInjectable (core.mjs:5872:38

Antes funcionaba bien  pero con la actualización ya lo dejo de hacer y ya no se muestra el modal en nuestra por fallas de la nueva versión de bamboo.
![Error](https://github.com/user-attachments/assets/a9a85d61-6208-47b2-88b0-7c94c520eb0d)
![Errores](https://github.com/user-attachments/assets/129e6771-b619-471a-aa28-824dce94c97d)

**Comment by t-juansanchez** [comment]
Hola @neftec99 no he podido reproducir tu error, este el package de la app, 
```
{
  "name": "lib-tester",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^17.3.0",
    "@angular/common": "^17.3.0",
    "@angular/compiler": "^17.3.0",
    "@angular/core": "^17.3.0",
    "@angular/forms": "^17.3.0",
    "@angular/platform-browser": "^17.3.0",
    "@angular/platform-browser-dynamic": "^17.3.0",
    "@angular/router": "^17.3.0",
    "@ti-tecnologico-de-monterrey-oficial/ds-ng": "^1.2.0",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^17.3.5",
    "@angular/cli": "^18.0.2",
    "@angular/compiler-cli": "^17.3.0",
    "@types/jasmine": "~5.1.0",
    "jasmine-core": "~5.1.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "typescript": "~5.4.2"
  }
}
```

Esta es la función de que manda llamar al dialogo

```
openModalComponent() {


    const data: ModalDataConfig = {
      title: 'Modal Title',
      subtitle: 'Modal Subtitle',
      content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
      size: 'large',
      type: 'action',
      primaryBtnLabel: 'Ok',
      primaryAction: () => window.alert('Primary action triggered!'),
    }

    this.matDialog.open(BmbModalComponent, { data });
  }
```

Podrías eliminar la carpeta  .angular para ver si ese es el problema
![image](https://github.com/user-attachments/assets/b8e68085-0ccd-4bbf-80fa-ce602db016dd)

Quedo atento a tu respuesta

**Comment by neftec99** [comment]
nosotros estamos utilizando angular 18 porque así nos pidieron que hiciéramos una actualización e incluyendo la versión de bambo en 2.1.

Entonces cual es el deber ser correrlo en angular 17 o 18? ya que se nos comento que actualizar el angular a la versión 18

Te comparto mi package.json

{
  "name": "TecSignEnvelope",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ngserve",
    "build": "ng build",
    "build:ssr": "ng run Tec.Sign.Envelope:server:dev",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular-devkit/build-angular": "^18.2.12",
    "@angular/animations": "^18.2.12",
    "@angular/cdk": "^18.2.14",
    "@angular/common": "^18.2.12",
    "@angular/compiler": "^18.2.12",
    "@angular/core": "^18.2.12",
    "@angular/forms": "^18.2.12",
    "@angular/localize": "^18.2.12",
    "@angular/material": "^18.2.14",
    "@angular/platform-browser": "^18.2.12",
    "@angular/platform-browser-dynamic": "^18.2.12",
    "@angular/platform-server": "^18.2.12",
    "@angular/router": "^18.2.12",
    "@ngrx/effects": "^18.1.1",
    "@ngrx/store": "^18.1.1",
    "@ngrx/store-devtools": "^18.1.1",
    "@ti-tecnologico-de-monterrey-oficial/ds-ng": "^1.2.0",
    "@types/cropperjs": "^1.3.0",
    "angular-cropperjs": "^14.0.1",
    "bootstrap": "^5.3.3",
    "cropperjs": "^1.6.2",
    "flowbite": "^2.3.0",
    "html2canvas": "^1.4.1",
    "http": "^0.0.1-security",
    "jquery": "^3.7.1",
    "material-design-icons": "^3.0.1",
    "material-symbols": "^0.17.1",
    "ng2-pdf-viewer": "^10.3.3",
    "rxjs": "^7.8.0",
    "sass": "^1.75.0",
    "tslib": "^2.4.0",
    "zone.js": "^0.14.4"
  },
  "devDependencies": {
    "@angular/cli": "^18.2.12",
    "@angular/compiler-cli": "^18.2.12",
    "@types/node": "^20.11.30",
    "tailwindcss": "^3.4.3",
    "typescript": "~5.4.3"
  }
}

Quedamos atento de su amable respuesta.

Saludos

**Comment by neftec99** [comment]
ya borramos la carpeta .Angular y dio el mismo resultado.

Si es posible nos podemos mandar una mensaje en teams para agendar una llamada seria mucho mejor el acercamiento.

Quedamos atentos. 

Saludos :)
