### ISSUE TITLE
Los layouts BmbWebTemplatesComponent no son compatibles con el router de Angular debido a su estructura altamente acoplada.

### ISSUE THREAD

**Issue by nachoritos01** [ti-tecnologico-de-monterrey-oficial/tec-design-system-ng#251]
**Is your feature request related to a problem? Please describe.**
Los layouts BmbWebTemplatesComponent no son compatibles con el router de Angular debido a su estructura altamente acoplada.

**Describe the solution you'd like**
Reestructurar los layouts para desacoplarlos del router o buscar una solución alterna más flexible.

**Describe alternatives you've considered**
Eliminar el comportamiento del los ` @switch (template()) ` dentro del componente BmbWebTemplatesComponent  dejando un contenedor que solo sirva para el <router-outlet> de esta manera brindan flexibilidad y dinamismo para el desarrollo, alternativamente crear un componente para estos contenedores que se usen en cada vista o  pagina

**Additional context**
![Captura de pantalla 2024-11-22 141950](https://github.com/user-attachments/assets/faa8b18a-69bd-4384-a792-7af9be2cf03e)

![Captura de pantalla 2024-11-21 114251](https://github.com/user-attachments/assets/df590817-a8e0-434a-b641-a03bddf8dfa5)

**Comment by t-juansanchez** [comment]
En la versión 1.2.1 de Bamboo se implementa una versión desacoplada de los mismos [Web templates](https://develop--65c3b4d1f966b98bb1f4e774.chromatic.com/?path=/docs/micro-componentes-web-templates-1-column-box--documentation)

**Comment by nachoritos01** [comment]
Gracias @t-juansanchez ,
