### ISSUE TITLE
Agregar mas de un error al BmbInputComponent 

### ISSUE THREAD

**Issue by nachoritos01** [ti-tecnologico-de-monterrey-oficial/tec-design-system-ng#255]
**Is your feature request related to a problem? Please describe.**
Agregar un manejador de errores que pueda manipular multiples errores o reglas, debido que BmbInputComponent solo contiene un unico error para mostrar

**Describe the solution you'd like**
Agregar un arreglo de errores para casos especificos, ejem: [requerido, solo numeros, formato especifico, etc]

**Describe alternatives you've considered**

**Additional context**

Solo acepta un error, una unica validacion, en casos especificos no se le puede notificar al usuario
![image](https://github.com/user-attachments/assets/05b66c79-4e76-45c6-a8b5-035cb3cc941d)

**Comment by t-juansanchez** [comment]
https://tecdemonterrey.atlassian.net/browse/DS01-1677

**Comment by t-juansanchez** [comment]
La versión 1.2.4 agrega el soporte para múltiples errores

https://develop--65c3b4d1f966b98bb1f4e774.chromatic.com/?path=/docs/micro-componentes-input--documentation
