### ISSUE TITLE
Se requiere agregar particularidades extras en BmbInputComponent para contemplar casos de [copy] [sho/hide]

### ISSUE THREAD

**Issue by nachoritos01** [ti-tecnologico-de-monterrey-oficial/tec-design-system-ng#256]
**Is your feature request related to a problem? Please describe.**
Se requiere agregar particularidades extras en BmbInputComponent para contemplar casos de [copy] [sho/hide] que se presenta en el diseño de figma

**Describe the solution you'd like**
agregar propiedades o crear nuevos componentes

**Describe alternatives you've considered**

**Additional context**

Se requiere agregar particularidades extras en BmbInputComponent para contemplar casos que se muestran en FIGMA
![image](https://github.com/user-attachments/assets/8ccbbc9b-a823-41b8-9a26-4d1bfda34ac0)

**Comment by t-juansanchez** [comment]
https://tecdemonterrey.atlassian.net/browse/DS01-1673

**Comment by t-juansanchez** [comment]
Resuelto en la versión 1.2.4 

La propiedad es Additional action.

https://develop--65c3b4d1f966b98bb1f4e774.chromatic.com/?path=/docs/micro-componentes-input--documentation
