### ISSUE TITLE
 Al colocar un texto muy largo en el input BmbCheckboxComponent este no se acopla al espacio 

### ISSUE THREAD

**Issue by nachoritos01** [ti-tecnologico-de-monterrey-oficial/tec-design-system-ng#257]
**Describe the bug**
 Al colocar un texto muy largo en el input checkbox este no se acopla al espacio

**To Reproduce**
1. Al colocar un texto muy largo en el input checkbox este no se acopla al espacio

**Expected behavior**
Que sea capaz de ajustarse a un espacio 

**Screenshots**
![image](https://github.com/user-attachments/assets/e3673fcd-4b02-44e5-884b-7bbdab10b393)

**Desktop (please complete the following information):**

- OS: WINDOWS 11
- Browser chrome
- Version 131.0.6778.86

**Smartphone (please complete the following information):**

**Additional context**
Verificar las propiedades CSS

**Comment by t-juansanchez** [comment]
https://tecdemonterrey.atlassian.net/browse/DS01-1676

**Comment by t-juansanchez** [comment]
Resuelto en la versión 1.2.4
