### ISSUE TITLE
BmbDropdownComponent es requerido tener un arreglo de objetos clave-valor

### ISSUE THREAD

**Issue by nachoritos01** [ti-tecnologico-de-monterrey-oficial/tec-design-system-ng#258]
**Is your feature request related to a problem? Please describe.**
Requiere un arreglo de objetos para enviar el ID; actualmente solo acepta arreglos de strings.

**Describe the solution you'd like**
Cambiar el arreglo de strings

**Describe alternatives you've considered**

**Additional context**
Actualmente se envia el valor del id sin enbargo BmbDropdownComponent solo permite el valor : ejemplo : [ banana] cuando es requerido el valor ejemplo [{valor: 1, clave: banana}]

![image](https://github.com/user-attachments/assets/3aeb241c-67b4-4cf7-ae2c-2b67e67b5937)

**Comment by t-juansanchez** [comment]
https://tecdemonterrey.atlassian.net/browse/DS01-1672

**Comment by t-juansanchez** [comment]
Corrección disponible en la versión 1.2.2
