### ISSUE TITLE
Actualmente solo se crea mediante un evento. BmbToastComponent

### ISSUE THREAD

**Issue by nachoritos01** [ti-tecnologico-de-monterrey-oficial/tec-design-system-ng#259]
**Is your feature request related to a problem? Please describe.**
Actualmente solo se ejecuta el componente BmbToastComponent a aprtir de un evento, cambiar esto para usar de manera individual

**Describe the solution you'd like**
crear otro componente 

**Describe alternatives you've considered**

**Additional context**

![image](https://github.com/user-attachments/assets/d840a1b5-2d02-4dfb-a1dd-c7d00d2df26a)

pantalla figma:
![image](https://github.com/user-attachments/assets/4e58ac6b-d11f-43e7-aeb6-d598a6e954a0)

**Comment by t-juansanchez** [comment]
https://tecdemonterrey.atlassian.net/browse/DS01-1653

**Comment by t-juansanchez** [comment]
Corrección disponible en la versión 1.2.2
