### ISSUE TITLE
BmbButtonDirective presenta deformidad en textos al cambiar de tamaño

### ISSUE THREAD

**Issue by nachoritos01** [ti-tecnologico-de-monterrey-oficial/tec-design-system-ng#262]
**Describe the bug**
BmbButtonDirective presenta deformidad en textos al cambiar la resolucion de la pantalla

**To Reproduce**

1. ajustar la pantalla

**Expected behavior**
Cambiar el tamaño de la fuente con  CSS media queries para prevenir este tipo de comportamientos

**Screenshots**
![image](https://github.com/user-attachments/assets/9098b42e-75c8-49c1-8892-00e42d1bde55)

**Desktop (please complete the following information):**

- OS: windows 11
- Browser chrome
- Version 131.0.6778.86

**Additional context**

**Comment by t-juansanchez** [comment]
https://tecdemonterrey.atlassian.net/browse/DS01-1674

**Comment by t-juansanchez** [comment]
Corrección disponible en la versión 1.2.2
