### ISSUE TITLE
Error al desplegar la modal se perdio la referencia R3InjectorError(Standalone[_BmbModalComponent])[MatDialogRef -> MatDialogRef -> 

### ISSUE THREAD

**Issue by nachoritos01** [ti-tecnologico-de-monterrey-oficial/tec-design-system-ng#290]
**Describe the bug**
Se detecto un error en la modal, al actualizar  en la ultima version  [v1.2.4](https://github.com/ti-tecnologico-de-monterrey-oficial/tec-design-system-ng/commit/8610307051f55d09088df65ab90c9995aa711db3)

En la version "1.1.3" no se presenta ese problema

**To Reproduce**
Actualizar la app en la nueva version

**Expected behavior**
dar click a boton que llama la modal

**Screenshots**

Se bajo de version para probar la version 1.1.3
` "@ti-tecnologico-de-monterrey-oficial/ds-ng": "1.1.3",`
![image](https://github.com/user-attachments/assets/7322c48d-cfec-433c-8df2-007e219d6c7e)

Error al probar la version 1.2.4
![image](https://github.com/user-attachments/assets/280edfc2-ffa5-433e-a462-09e514a835c9)

**Desktop (please complete the following information):**

- OS: [e.g. iOS] windows 11
- Browser [e.g. chrome, safari] Chrome  
- Version [e.g. 22] Versión 131.0.6778.205 (Build oficial) (64 bits)

**Additional context**

**Comment by t-juansanchez** [comment]
la version 1.2.X requiere Angular 18 (cumpliendo el requerimiento de infraestructura), puedes confirmar que tu proyecto este en Angular 18?

**Comment by nachoritos01** [comment]
Si, lo tengo en la version 18

**Comment by nachoritos01** [comment]
Corregido actualizando las dependencias de "@angular/cdk: ^18.2.14" y "@angular/material": ^18.2.14,", por defaul al usar ng add @angular/material te instala la version 17 que es lo que ocasionaba el problema
