### ISSUE TITLE
Issue BmbCardComponent

### ISSUE THREAD

**Issue by OsvaldoITESM** [ti-tecnologico-de-monterrey-oficial/tec-design-system-ng#66]
**Componente**: BmbCardComponent

**Issue**: Al implementar un componente card principal **solo** pasando como propiedad el "content" y dicho contenido son componentes card secundarios, el componente card principal toma como header, el header de mi ultimo componente card secundario. Pasa la misma situación con el footer.

Adjunto imagen para mejor visualización.

<img width="953" alt="image" src="https://github.com/ti-tecnologico-de-monterrey-oficial/tec-design-system-ng/assets/156938162/89ed925b-e200-4fde-87fe-484b08dd8254">

**Comment by t-juansanchez** [comment]
La implementación cambio un poco, ahora para utilizar los distintos elementos de la card es necesario importar los componentes BmbCardHeader, BmbCardContent y BmbCardFooter
