### ISSUE TITLE
Issue BmbSidebarComponent

### ISSUE THREAD

**Issue by OsvaldoITESM** [ti-tecnologico-de-monterrey-oficial/tec-design-system-ng#67]
**Componente:** BmbSidebarComponent

**Issue:** Al implementar el sideBar y topBar, el componente sideBar logra ocultar el contenido del topBar en este caso el logo del topBar. Se implementa utilizando con pantalla de 14 pulgadas con resolución de 1920 x 1080px.

Adjunto imagen para mas detalle.

<img width="956" alt="image" src="https://github.com/ti-tecnologico-de-monterrey-oficial/tec-design-system-ng/assets/156938162/52889123-adbf-4674-a502-ce3581352755">

**Comment by t-juansanchez** [comment]
@LizTec57 agregó una media query en el alto y evitar este comportamiento.

![image](https://github.com/user-attachments/assets/d9597a97-f918-47b5-ba7d-9ca4737e6b50)
